apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlOakEwTURZeApNVEl4TVRWYUZ3MDBOakEwTURZeE1USXhNVFZhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDbis1U1hmVGtoRkk1S1h0Ry9Odm9DeTFCa2VrUHZjanRUREJDK01GejYxRjFwZmk4aQpISFcvOG11S2JKL0htMlVGWHVRbGQ5Tyt1TzFBOFRibzlrNElHK1Q3Ykl0ZHhnWVJOZ2tOUndkdWtQMWdyTFJuCnRpTXF5Q2xFY2tPTXVOSk5TM1BjbEtKdHM2b1ZPNmgxOUxSR00rc3RDYm84OXYxR3Bxa2hDbzAraTZJd0hGYmkKRGtOOEQ1TXRsY29VV292eWhzTHZYdjB4b1hSVlhhdUdMSDAyYjN1SHZia0UrbFQ3K2JYUU9GNW9tUXJUYU00WQpORmRXdFlJWVVta1hHQlAwVktUMnFGZUk2SEhTcHM0V2M0TE1mZkprWmR3UWpxT0FGNGtnUEY4Q0dVNStBdUxFCkJNdU5HdGZrY29ZUVdIbHFJYzlTWFl4S2EwVm81QmFZbUVBcEFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlRVZzBLZGMyZ2Fhb2ZmSnRoUwo1U0tvKzhhalJqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFEUS8vanhwdVFwOXBQSmhlMHlvSWNhUHZkS3l2Cm8rd1NIVzRCbmhTOVFHZ0daUGJSTkhydWVTdWo5RnRqbjNjYS95VGVMQWhYSWJTVVI2cE81dlJKNGk3djI4ZisKTXNKOEdVaURQMzlsMXVPZVRvazlCb3JkQS84b1UzYWFyRU9XbEJ0TnU1Y2hGSWhpNFNlQW5jOGtucFFWQnFnZAp1bVNwaFNEb1QwclJwdXhGbHRZTzEyZFBncFBseGJ2aFBOYThqcXRIUFcxaTJTKytmMVo2Yy85RFE3Z05iUXY1Cm5ua2lJd05sTlN6NFUvVVd6aGhEQ1Q1cVVqZHpPQmZqNStMTzhRWVpRaExRMDMwZENJOUhHRS9GUFhIQUEvZzEKRlV6UWdhdVFobVdHVEMwbExRRklxckMzOEdTazFDMHBjNkVDbXd2L1hWMGwxbHQ0ZGxYSDAweEhTZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://6525a4f4-3d5e-49ee-b9c6-091c3da51a1a.k8s.ondigitalocean.com
  name: do-fra1-demo-kpi-k8s
contexts:
- context:
    cluster: do-fra1-demo-kpi-k8s
    user: do-fra1-demo-kpi-k8s-admin
  name: do-fra1-demo-kpi-k8s
current-context: do-fra1-demo-kpi-k8s
kind: Config
preferences: {}
users:
- name: do-fra1-demo-kpi-k8s-admin
  user:
    token: dop_v1_876a795a3073b98ab06e97c908d2a9ba9bc02fc95d5393322406ba9d6a423f73
