name: hive

services:
  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend

  communication-control:
    image: reghiveyuliaim32.azurecr.io/communication-control:1.0
    container_name: com-control
    restart: always
    environment:
      Redis__ConnectionString: "redis:6379,abortConnect=false"
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend: