apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
  annotations:
    # DigitalOcean load balancer size (s-1vcpu-1gb is cheapest)
    service.beta.kubernetes.io/do-loadbalancer-size-slug: "lb-small"
    # Optional: reserve a static DO reserved IP
    # service.beta.kubernetes.io/do-loadbalancer-floating-ip: "<your-reserved-ip>"
    service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
    # Redirect HTTP → HTTPS at the LB level (optional, can also be done in nginx)
    # service.beta.kubernetes.io/do-loadbalancer-http-ports: "80"
    # service.beta.kubernetes.io/do-loadbalancer-https-ports: "443"
    # Name shown in the DO control panel
    service.beta.kubernetes.io/do-loadbalancer-name: "hive-emulator-lb"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster # всі ноди проходять health check LB
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/component: controller
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
    - name: https
      port: 443
      targetPort: https
      protocol: TCP
